job/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::get('/', 'HomeController@index')->name('home');
Route::get('clear', 'HomeController@clearCache')->name('clear_cache');

Route::get('new-register', 'HomeController@newRegister')->name('new_register');
Route::get('job-seeker-register', 'UserController@registerJobSeeker')->name('register_job_seeker');
Route::post('job-seeker-register', 'UserController@registerJobSeekerPost');

Route::get('employer-register', 'UserController@registerEmployer')->name('register_employer');
Route::post('employer-register', 'UserController@registerEmployerPost');

// Route::post('get-states-options', 'LocationController@getStatesOption')->name('get_state_option_by_country');

Route::get('apply_job', function (){
    return redirect(route('home'));
});
Route::post('apply_job', ['as' => 'apply_job', 'uses'=>'JobController@applyJob']);
Route::post('flag-job/{id}', ['as' => 'flag_job_post', 'uses'=>'JobController@flagJob']);
Route::post('share-by-email', ['as' => 'share_by_email', 'uses'=>'JobController@shareByEmail']);
Route::get('employer/{user_name}/jobs', 'JobController@jobsByEmployer')->name('jobs_by_employer');
Route::post('follow-unfollow', 'FollowerController@followUnfollow')->name('follow_unfollow');


Route::get('jobs/', 'JobController@jobsListing')->name('jobs_listing');

Route::get('p/{slug}', ['as' => 'single_page', 'uses' => 'PostController@showPage']);

Route::get('blog', 'PostController@blogIndex')->name('blog_index');
Route::get('blog/{slug}', 'PostController@view')->name('blog_post_single');

Route::get('pricing', 'HomeController@pricing')->name('pricing');

Route::get('contact-us', 'HomeController@contactUs')->name('contact_us');
Route::post('contact-us', 'HomeController@contactUsPost');



//Dashboard Route
Route::group(['prefix'=>'dashboard', 'middleware' => 'dashboard'], function(){
    Route::get('/', 'DashboardController@dashboard')->name('dashboard');

    Route::get('applied-jobs', 'DashboardController@dashboard')->name('applied_jobs');


    Route::group(['middleware'=>'admin_agent_employer'], function(){

        Route::group(['prefix'=>'employer'], function(){

            Route::group(['prefix'=>'job'], function(){
                Route::get('new', 'JobController@newJob')->name('post_new_job');
                Route::post('new', 'JobController@newJobPost');
                Route::get('edit/{job_id}', 'JobController@edit')->name('edit_job');
                Route::post('edit/{job_id}', 'JobController@update');
                Route::get('posted', 'JobController@postedJobs')->name('posted_jobs');
            });

            Route::get('applicant', 'UserController@employerApplicant')->name('employer_applicant');
            Route::get('shortlisted', 'UserController@shortlistedApplicant')->name('shortlisted_applicant');
            Route::get('applicant/{application_id}/shortlist', 'UserController@makeShortList')->name('make_short_list');
            Route::get('applicant/{application_id}/removeshortlist', 'UserController@removeShortList')->name('remove_short_list');

            Route::get('profile', 'UserController@employerProfile')->name('employer_profile');
            Route::post('profile', 'UserController@employerProfilePost');

        });
        Route::group(['prefix'=>'jobs'], function(){
            Route::get('/', 'JobController@pendingJobs')->name('pending_jobs');
            Route::get('pending', 'JobController@approvedJobs')->name('approved_jobs');
            Route::get('blocked', 'JobController@blockedJobs')->name('blocked_jobs');
            Route::get('status/{id}/{status}', 'JobController@statusChange')->name('job_status_change');

            Route::get('applicants/{job_id}', 'JobController@jobApplicants')->name('job_applicants');
        });


        Route::get('flagged', 'JobController@flaggedMessage')->name('flagged_jobs');


        Route::group(['prefix'=>'cms'], function(){
            Route::get('/', 'PostController@index')->name('pages');
            Route::get('page/add', 'PostController@addPage')->name('add_page');
            Route::post('page/add', 'PostController@store');

            Route::get('page/edit/{id}', 'PostController@pageEdit')->name('page_edit');
            Route::post('page/edit/{id}', 'PostController@pageEditPost');

            Route::get('posts', 'PostController@indexPost')->name('posts');
            Route::get('post/add', 'PostController@addPost')->name('add_post');
            Route::post('post/add', 'PostController@storePost');

            Route::get('post/edit/{id}', 'PostController@postEdit')->name('post_edit');
            Route::post('post/edit/{id}', 'PostController@postUpdate');

        });

    });


    Route::group(['middleware'=>'only_admin_access'], function(){

        Route::group(['prefix'=>'categories'], function(){
            Route::get('/', ['as'=>'dashboard_categories', 'uses' => 'CategoriesController@index']);
            Route::post('/', ['uses' => 'CategoriesController@store']);

            Route::get('edit/{id}', ['as'=>'edit_categories', 'uses' => 'CategoriesController@edit']);
            Route::post('edit/{id}', ['uses' => 'CategoriesController@update']);

            Route::post('delete-categories', ['as'=>'delete_categories', 'uses' => 'CategoriesController@destroy']);
        });

        //Settings
        Route::group(['prefix'=>'settings'], function(){
            Route::get('/', 'SettingsController@GeneralSettings')->name('general_settings');

            Route::get('theme-settings', 'SettingsController@ThemeSettings')->name('theme_settings');
            // Route::get('gateways', 'SettingsController@GatewaySettings')->name('gateways_settings');
            // Route::get('pricing', 'SettingsController@PricingSettings')->name('pricing_settings');
            // Route::post('pricing', 'SettingsController@PricingSave');

            //Save settings / options
            Route::post('save-settings', ['as'=>'save_settings', 'uses' => 'SettingsController@update']);
        });
    });


    Route::group(['prefix'=>'payments'], function() {
        Route::get('/', 'PaymentController@index')->name('payments');

        Route::get('view/{id}', ['as'=>'payment_view', 'uses' => 'PaymentController@view']);
        Route::get('status-change/{id}/{status}', ['as'=>'status_change', 'uses' => 'PaymentController@markSuccess']);
    });

    Route::group(['prefix'=>'u'], function(){
        Route::get('applied-jobs', 'UserController@appliedJobs')->name('applied_jobs');
        Route::get('profile', 'UserController@profile')->name('profile');
        Route::get('profile/edit', 'UserController@profileEdit')->name('profile_edit');
        Route::post('profile/edit', 'UserController@profileEditPost');

        Route::group(['prefix'=>'users'], function(){
            Route::get('/', 'UserController@index')->name('users');
            Route::get('view/{slug}', ['as'=>'users_view', 'uses' => 'UserController@show']);
            Route::get('user_status/{id}/{status}', 'UserController@statusChange')->name('user_status');

            //Edit
            Route::get('edit/{id}', ['as'=>'users_edit', 'uses' => 'UserController@profileEdit']);
            Route::post('edit/{id}', ['uses' => 'UserController@profileEditPost']);
            Route::get('profile/change-avatar/{id}', ['as'=>'change_avatar', 'uses' => 'UserController@changeAvatar']);
            //CV
           
        });
        //CV
            Route::get('/cv/create', 'UserController@createCV')->name('create_new_cv');
            Route::post('/cv/create', 'UserController@storeCV');
            Route::get('/cv/view/{id}', 'UserController@viewCV')->name('view_cv');
            Route::get('/cv/edit/{id}', 'UserController@editCV');
            Route::post('/cv/edit/{id}', 'UserController@updateCV');
        /**
         * Change Password route
         */
        Route::group(['prefix' => 'account'], function() {
            Route::get('change-password', ['as' => 'change_password', 'uses' => 'UserController@changePassword']);
            Route::post('change-password', 'UserController@changePasswordPost');
        });

    });

    Route::group(['prefix' => 'account'], function() {
        Route::get('change-password', 'UserController@changePassword')->name('change_password');
        Route::post('change-password', 'UserController@changePasswordPost');
    });

});


//Single Sigment View
Route::get('view-job/{id}', 'JobController@view')->name('job_view');

job/app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $guarded = [];

    public function getFeatureImageUriAttribute(){
        if ($this->feature_image){
            return asset('storage/uploads/images/blog/full/'.$this->feature_image);
        }
        return asset('assets/images/placeholder.png');
    }
    public function getFeatureImageThumbUriAttribute(){
        if ($this->feature_image){
            return asset('storage/uploads/images/blog/thumb/'.$this->feature_image);
        }
        return asset('assets/images/placeholder.png');
    }

    public function author(){
        return $this->belongsTo(User::class, 'user_id');
    }

}

job/resources/views/blog-view.blade.php
@extends('layouts.theme')

@section('content')
    <div class="blog-single-page bg-white">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="blog-single-title mt-5">
                        <h1>{{$post->title}}</h1>
                    </div>

                    <div class="blog-single-meta pt-3 mt-3">
                        <span><i class="la la-user"></i> {{$post->author->name}} </span>
                        <span><i class="la la-clock-o"></i> {{$post->created_at->diffForHumans()}} </span>
                        <span><i class="la la-eye"></i> {{$post->views}} </span>
                    </div>
                </div>
            </div>
        </div>

        @if($post->feature_image)
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="blog-single-title mt-5">

                            <img src="{{$post->feature_image_uri}}" title="{{$post->title}}" alt="{{$post->title}}" class="img-fluid" />

                        </div>
                    </div>
                </div>
            </div>
        @endif

        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <div class="blog-single-content py-5">
                        {!! $post->post_content !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

job/resources/views/checkout.blade.php
@extends('layouts.theme')

@section('content')
    <div class="checkout-page py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <h1>@lang('app.checkout')</h1>
                </div>
            </div>
        </div>
    </div>


    <div class="checkout-page bg-white py-5">

        @php
        $user= auth()->user();
        @endphp

        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <div class="checkout-form pt-3 pb-5">

                        <form method="post">
                            @csrf

                        <p>{{$user->name}}</p>
                        <h4>Package: {{$package->package_name}}</h4>
                        <p>@lang('app.premium_job') : {{$package->premium_job}}</p>
                        <p class="text-success">@lang('app.price') : {!! get_amount($package->price) !!}</p>


                        <h4 class="my-5 text-muted">Choose your gateway</h4>

                        <div class="checkout-gateways-wrap">
                            <div class="checkout-gateway bg-light p-3 my-3">
                                <label>
                                    <input type="radio" name="gateway" value="paypal" checked="checked"> @lang('app.paypal')
                                </label>
                            </div>

                            <div class="checkout-gateway bg-light p-3 my-3">
                                <label>
                                    <input type="radio" name="gateway" value="stripe"> @lang('app.stripe')
                                </label>
                            </div>

                            <div class="checkout-gateway bg-light p-3 my-3">
                                <label>
                                    <input type="radio" name="gateway" value="bank_transfer"> @lang('app.bank_transfer')
                                </label>
                            </div>
                        </div>

                            <button class="btn btn-success btn-lg"><i class="la la-cart-arrow-down"></i> @lang('app.checkout')</button>


                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

job/resources/views/contact_us.blade.php
@extends('layouts.theme')

@section('content')
    <div class="blog-single-page bg-white">
        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <div class="blog-single-title mt-5">
                        <h1>@lang('app.contact_us')</h1>
                    </div>

                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <div class="blog-single-content pt-3 pb-5">


                        @include('admin.flash_msg')
                        <form method="POST" action="">
                            @csrf

                            <div class="form-group row{{ $errors->has('name') ? ' has-error' : '' }}">
                                <label for="name" class="col-md-4 control-label">@lang('app.name') <span class="text-danger">*</span></label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control {{e_form_invalid_class('name', $errors)}}" name="name" value="{{ old('name') }}">
                                    {!! e_form_error('name', $errors) !!}
                                </div>
                            </div>

                            <div class="form-group row{{ $errors->has('email') ? ' has-error' : '' }}">
                                <label for="email" class="col-md-4 control-label">@lang('app.email_address')  <span class="text-danger">*</span></label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control {{e_form_invalid_class('email', $errors)}}" name="email" value="{{ old('email') }}" >
                                    {!! e_form_error('email', $errors) !!}
                                </div>
                            </div>

                            <div class="form-group row{{ $errors->has('subject') ? ' has-error' : '' }}">
                                <label for="subject" class="col-md-4 control-label">@lang('app.subject')  <span class="text-danger">*</span></label>

                                <div class="col-md-6">
                                    <input id="subject" type="text" class="form-control {{e_form_invalid_class('subject', $errors)}}" name="subject" value="{{ old('subject') }}" >
                                    {!! e_form_error('subject', $errors) !!}
                                </div>
                            </div>

                            <div class="form-group row{{ $errors->has('message') ? ' has-error' : '' }}">
                                <label for="message" class="col-md-4 control-label">@lang('app.message')</label>
                                <div class="col-md-6">
                                    <textarea name="message" class="form-control {{e_form_invalid_class('message', $errors)}}" rows="7">{{ old('message') }}</textarea>
                                    {!! e_form_error('message', $errors) !!}
                                </div>
                            </div>


                            <div class="form-group row">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-success">
                                        <i class="la la-envelope-o"></i> @lang('app.send_feedback')
                                    </button>
                                </div>
                            </div>
                        </form>




                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

job/resources/views/editCV.blade.php
@extends('layouts.theme')

@section('content')
    <div class="blog-single-page bg-white">
        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <div class="blog-single-title mt-5">
                        <h1>Edit your CV</h1>
                    </div>

                </div>
            </div>
        </div>

        <div class="container">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form method="POST" action="">
                @csrf
                <div class="row">
                    <div class="col-md-8">
                        <div class="blog-single-content pt-3 pb-5">
                            <div class="form-group row">
                                <label for="name" class="col-md-4 control-label">Fullname</label>
                                <div class="col-md-6">
                                    <input id="fullname" type="text" class="form-control" name="fullname" value="{{$editCV['fullname']}}">
                                    {!! e_form_error('fullname', $errors) !!}

                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="name" class="col-md-4 control-label">Date of birth</label>
                                <div class="col-md-6">
                                    <input id="dayofbirth" type="date" class="form-control" name="dayofbirth" value="{{$editCV['dayofbirth']}}">
                                    {!! e_form_error('dayofbirth', $errors) !!}

                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="name" class="col-md-4 control-label">Education</label>
                                <div class="col-md-6">
                                    <!-- <input id="education" type="text" class="form-control" name="education" value="{{$editCV['education']}}"> -->
                                    <textarea id="education" type="text" class="form-control" name="education">{{$editCV['education']}}</textarea>
                                    {!! e_form_error('education', $errors) !!}

                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="name" class="col-md-4 control-label">Work Experience</label>
                                <div class="col-md-6">
                                   <!--  <input id="working_exp" type="text" class="form-control" name="working_exp" value="{{$editCV['working_exp']}}"> -->
                                    <textarea id="working_exp" type="text" class="form-control" name="working_exp">{{$editCV['working_exp']}}</textarea>
                                    {!! e_form_error('working_exp', $errors) !!}

                                </div>
                            </div>
                            <!-- <div class="form-group row">
                                <label for="name" class="col-md-4 control-label">Personal Skill</label>
                                <div class="col-md-6">
                                    <textarea id="personal_skill" type="text" class="form-control" name="personal_skill">{{$editCV['personal_skill']}}</textarea>
                                    {!! e_form_error('personal_skill', $errors) !!}

                                </div>
                            </div> -->
                            <div class="form-group row">
                                <label for="name" class="col-md-4 control-label">Project participation</label>
                                <div class="col-md-6">
                                    <textarea id="project_participation" type="text" class="form-control" name="project_participation">{{$editCV['project_participation']}}</textarea>
                                    {!! e_form_error('project_participation', $errors) !!}

                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="name" class="col-md-4 control-label">Activities</label>
                                <div class="col-md-6">
                                    <textarea id="activities" type="text" class="form-control" name="activities">{{$editCV['activities']}}</textarea>
                                    {!! e_form_error('activities', $errors) !!}

                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="name" class="col-md-4 control-label">Goal Career</label>
                                <div class="col-md-6">
                                    <textarea id="goal_career" type="text" class="form-control" name="goal_career" >{{$editCV['goal_career']}}</textarea>
                                    {!! e_form_error('goal_career', $errors) !!}

                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="name" class="col-md-4 control-label">Certificate</label>
                                <div class="col-md-6">
                                    <textarea id="certificate" type="text" class="form-control" name="certificate">{{$editCV['certificate']}}</textarea>
                                    {!! e_form_error('certificate', $errors) !!}

                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="name" class="col-md-4 control-label">My Hobby</label>
                                <div class="col-md-6">
                                    <textarea id="your_hobby" type="text" class="form-control" name="your_hobby">{{$editCV['your_hobby']}}</textarea>
                                    {!! e_form_error('your_hobby', $errors) !!}

                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-6">
                                    <input id="user_id" type="hidden" class="form-control" name="user_id" value="">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="name" class="col-md-4 control-label">Category</label>
                                <div class="col-md-6">
                                    <select name="category_id" class="form-control">
                                    @foreach($getCategory as $value)
                                        <option value="{{$value['id']}}">{{$value['category_name']}}</option>
                                    @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-success">
                                        UPDATE CV
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <table id="skill" class=" table order-list">
                            <thead>
                                <tr>
                                    <td>Your skills</td>
                                    <td>progress</td>
                                    <td></td>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($skill as $key => $value)
                                <tr>

                                    <td>
                                        <input style="width: 300px;" type="text" class="form-control language" name="language[]" value="{{$key}}" />
                                    </td>
                                    <td>
                                        <select style="padding:0;" class="form-control" class="progress" name="progress[]">
                                            <option value = "10">10%</option>
                                            <option value = "20">20%</option>
                                            <option value = "30">30%</option>
                                            <option value = "40">40%</option>
                                            <option value = "50">50%</option>
                                            <option value = "60">60%</option>
                                            <option value = "70">70%</option>
                                            <option value = "80">80%</option>
                                            <option value = "90">90%</option>
                                            <option value = "100">100%</option>
                                        </select>
                                    </td>
                                    <th class="col-sm-2">
                                        <a class="deleteRow"></a>
                                    </th>

                                </tr>
                                @endforeach

                            </tbody>

                            <tfoot>
                                <tr>
                                    <td colspan="5" style="text-align: left;">
                                        <input type="button" class="btn btn-lg btn-block" style="background-color: #38c172;" id="addrow" value="Add Row" />
                                    </td>
                                </tr>
                                <tr>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type='text/javascript'>
    $(document).ready(function() {
        // $('form').on('submit', function(){
        //     var json = html2json();
        //     console.log($('input.total_skill').val())
        //     //console.log(json);
        //     return false;
        // })
        var counter = 0;

        $("#addrow").on("click", function() {
            var newRow = $("<tr>");
            var cols = "";

            cols += '<td><input style="width: 300px;" type="text" class="form-control" name="language[]"/></td>';
            cols += '<td><select style="padding:0;" class="form-control" name="progress[]">' +
                '<option value = "10">10%</option>' +
                '<option value = "20">20%</option>' +
                '<option value = "30">30%</option>' +
                '<option value = "40">40%</option>' +
                '<option value = "50">50%</option>' +
                '<option value = "60">60%</option>' +
                '<option value = "70">70%</option>' +
                '<option value = "80">80%</option>' +
                '<option value = "90">90%</option>' +
                '<option value = "100">100%</option>' +
                '</select></td>';

            cols += '<td><input type="button" class="ibtnDel btn btn-md btn-danger "  value="Delete"></td>';
            newRow.append(cols);
            $("table.order-list").append(newRow);
            counter++;
        });



        $("table.order-list").on("click", ".ibtnDel", function(event) {
            $(this).closest("tr").remove();
            counter -= 1
        });


    });

    function calculateRow(row) {
        var price = +row.find('input[name^="price"]').val();

    }

    function calculateGrandTotal() {
        var grandTotal = 0;
        $("table.order-list").find('input[name^="price"]').each(function() {
            grandTotal += +$(this).val();
        });
        $("#grandtotal").text(grandTotal.toFixed(2));
    }
</script>
@endsection

job/resources/views/index.blade.php
@extends('layouts.theme')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            <h2>Homepage</h2>


        </div>
    </div>
</div>
@endsection

job/resources/views/new_register.blade.php
@extends('layouts.theme')

@section('content')
    <div class="new-registration-page py-4">
        <div class="container">
            <div class="row">
                <div class="col-md-6" style="margin-left: 300px;">
                    <div class="register-account-box jf-shadow p-3">
                        <h2>@lang('app.job_seeker')</h2>
                        <p class="icon"><i class="la la-user"></i> </p>
                        <p>@lang('app.job_seeker_new_desc')</p>
                        <a href="{{route('register_job_seeker')}}" class="btn btn-success"><i class="la la-user-plus"></i> @lang('app.register_account') </a>
                    </div>
                </div>
               <!--  <div class="col-md-6">
                    <div class="register-account-box jf-shadow  p-3">
                        <h2>@lang('app.employer')</h2>
                        <p class="icon"><i class="la la-black-tie"></i> </p>
                        <p>@lang('app.employer_new_desc')</p>
                        <a href="{{route('register_employer')}}" class="btn btn-success"><i class="la la-user-plus"></i> @lang('app.register_account') </a>
                    </div>
                </div> -->
            </div>
        </div>
    </div>
@endsection