job/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::get('/', 'HomeController@index')->name('home');
Route::get('clear', 'HomeController@clearCache')->name('clear_cache');

Route::get('new-register', 'HomeController@newRegister')->name('new_register');
Route::get('job-seeker-register', 'UserController@registerJobSeeker')->name('register_job_seeker');
Route::post('job-seeker-register', 'UserController@registerJobSeekerPost');

Route::get('employer-register', 'UserController@registerEmployer')->name('register_employer');
Route::post('employer-register', 'UserController@registerEmployerPost');

// Route::post('get-states-options', 'LocationController@getStatesOption')->name('get_state_option_by_country');

Route::get('apply_job', function (){
    return redirect(route('home'));
});
Route::post('apply_job', ['as' => 'apply_job', 'uses'=>'JobController@applyJob']);
Route::post('flag-job/{id}', ['as' => 'flag_job_post', 'uses'=>'JobController@flagJob']);
Route::post('share-by-email', ['as' => 'share_by_email', 'uses'=>'JobController@shareByEmail']);
Route::get('employer/{user_name}/jobs', 'JobController@jobsByEmployer')->name('jobs_by_employer');
Route::post('follow-unfollow', 'FollowerController@followUnfollow')->name('follow_unfollow');


Route::get('jobs/', 'JobController@jobsListing')->name('jobs_listing');

Route::get('p/{slug}', ['as' => 'single_page', 'uses' => 'PostController@showPage']);

Route::get('blog', 'PostController@blogIndex')->name('blog_index');
Route::get('blog/{slug}', 'PostController@view')->name('blog_post_single');

Route::get('pricing', 'HomeController@pricing')->name('pricing');

Route::get('contact-us', 'HomeController@contactUs')->name('contact_us');
Route::post('contact-us', 'HomeController@contactUsPost');



//Dashboard Route
Route::group(['prefix'=>'dashboard', 'middleware' => 'dashboard'], function(){
    Route::get('/', 'DashboardController@dashboard')->name('dashboard');

    Route::get('applied-jobs', 'DashboardController@dashboard')->name('applied_jobs');


    Route::group(['middleware'=>'admin_agent_employer'], function(){

        Route::group(['prefix'=>'employer'], function(){

            Route::group(['prefix'=>'job'], function(){
                Route::get('new', 'JobController@newJob')->name('post_new_job');
                Route::post('new', 'JobController@newJobPost');
                Route::get('edit/{job_id}', 'JobController@edit')->name('edit_job');
                Route::post('edit/{job_id}', 'JobController@update');
                Route::get('posted', 'JobController@postedJobs')->name('posted_jobs');
            });

            Route::get('applicant', 'UserController@employerApplicant')->name('employer_applicant');
            Route::get('shortlisted', 'UserController@shortlistedApplicant')->name('shortlisted_applicant');
            Route::get('applicant/{application_id}/shortlist', 'UserController@makeShortList')->name('make_short_list');
            Route::get('applicant/{application_id}/removeshortlist', 'UserController@removeShortList')->name('remove_short_list');

            Route::get('profile', 'UserController@employerProfile')->name('employer_profile');
            Route::post('profile', 'UserController@employerProfilePost');

        });
        Route::group(['prefix'=>'jobs'], function(){
            Route::get('/', 'JobController@pendingJobs')->name('pending_jobs');
            Route::get('pending', 'JobController@approvedJobs')->name('approved_jobs');
            Route::get('blocked', 'JobController@blockedJobs')->name('blocked_jobs');
            Route::get('status/{id}/{status}', 'JobController@statusChange')->name('job_status_change');

            Route::get('applicants/{job_id}', 'JobController@jobApplicants')->name('job_applicants');
        });


        Route::get('flagged', 'JobController@flaggedMessage')->name('flagged_jobs');


        Route::group(['prefix'=>'cms'], function(){
            Route::get('/', 'PostController@index')->name('pages');
            Route::get('page/add', 'PostController@addPage')->name('add_page');
            Route::post('page/add', 'PostController@store');

            Route::get('page/edit/{id}', 'PostController@pageEdit')->name('page_edit');
            Route::post('page/edit/{id}', 'PostController@pageEditPost');

            Route::get('posts', 'PostController@indexPost')->name('posts');
            Route::get('post/add', 'PostController@addPost')->name('add_post');
            Route::post('post/add', 'PostController@storePost');

            Route::get('post/edit/{id}', 'PostController@postEdit')->name('post_edit');
            Route::post('post/edit/{id}', 'PostController@postUpdate');

        });

    });


    Route::group(['middleware'=>'only_admin_access'], function(){

        Route::group(['prefix'=>'categories'], function(){
            Route::get('/', ['as'=>'dashboard_categories', 'uses' => 'CategoriesController@index']);
            Route::post('/', ['uses' => 'CategoriesController@store']);

            Route::get('edit/{id}', ['as'=>'edit_categories', 'uses' => 'CategoriesController@edit']);
            Route::post('edit/{id}', ['uses' => 'CategoriesController@update']);

            Route::post('delete-categories', ['as'=>'delete_categories', 'uses' => 'CategoriesController@destroy']);
        });

        //Settings
        Route::group(['prefix'=>'settings'], function(){
            Route::get('/', 'SettingsController@GeneralSettings')->name('general_settings');

            Route::get('theme-settings', 'SettingsController@ThemeSettings')->name('theme_settings');
            // Route::get('gateways', 'SettingsController@GatewaySettings')->name('gateways_settings');
            // Route::get('pricing', 'SettingsController@PricingSettings')->name('pricing_settings');
            // Route::post('pricing', 'SettingsController@PricingSave');

            //Save settings / options
            Route::post('save-settings', ['as'=>'save_settings', 'uses' => 'SettingsController@update']);
        });
    });


    Route::group(['prefix'=>'payments'], function() {
        Route::get('/', 'PaymentController@index')->name('payments');

        Route::get('view/{id}', ['as'=>'payment_view', 'uses' => 'PaymentController@view']);
        Route::get('status-change/{id}/{status}', ['as'=>'status_change', 'uses' => 'PaymentController@markSuccess']);
    });

    Route::group(['prefix'=>'u'], function(){
        Route::get('applied-jobs', 'UserController@appliedJobs')->name('applied_jobs');
        Route::get('profile', 'UserController@profile')->name('profile');
        Route::get('profile/edit', 'UserController@profileEdit')->name('profile_edit');
        Route::post('profile/edit', 'UserController@profileEditPost');

        Route::group(['prefix'=>'users'], function(){
            Route::get('/', 'UserController@index')->name('users');
            Route::get('view/{slug}', ['as'=>'users_view', 'uses' => 'UserController@show']);
            Route::get('user_status/{id}/{status}', 'UserController@statusChange')->name('user_status');

            //Edit
            Route::get('edit/{id}', ['as'=>'users_edit', 'uses' => 'UserController@profileEdit']);
            Route::post('edit/{id}', ['uses' => 'UserController@profileEditPost']);
            Route::get('profile/change-avatar/{id}', ['as'=>'change_avatar', 'uses' => 'UserController@changeAvatar']);
            //CV
           
        });
        //CV
            Route::get('/cv/create', 'UserController@createCV')->name('create_new_cv');
            Route::post('/cv/create', 'UserController@storeCV');
            Route::get('/cv/view/{id}', 'UserController@viewCV')->name('view_cv');
            Route::get('/cv/edit/{id}', 'UserController@editCV');
            Route::post('/cv/edit/{id}', 'UserController@updateCV');
        /**
         * Change Password route
         */
        Route::group(['prefix' => 'account'], function() {
            Route::get('change-password', ['as' => 'change_password', 'uses' => 'UserController@changePassword']);
            Route::post('change-password', 'UserController@changePasswordPost');
        });

    });

    Route::group(['prefix' => 'account'], function() {
        Route::get('change-password', 'UserController@changePassword')->name('change_password');
        Route::post('change-password', 'UserController@changePasswordPost');
    });

});


//Single Sigment View
Route::get('view-job/{id}', 'JobController@view')->name('job_view');

job/app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $guarded = [];

    public function getFeatureImageUriAttribute(){
        if ($this->feature_image){
            return asset('storage/uploads/images/blog/full/'.$this->feature_image);
        }
        return asset('assets/images/placeholder.png');
    }
    public function getFeatureImageThumbUriAttribute(){
        if ($this->feature_image){
            return asset('storage/uploads/images/blog/thumb/'.$this->feature_image);
        }
        return asset('assets/images/placeholder.png');
    }

    public function author(){
        return $this->belongsTo(User::class, 'user_id');
    }

}

job/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Auth;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    public function jobs(){
        return $this->hasMany(Job::class)->orderBy('id', 'desc');
    }
    public function is_user(){
        return $this->user_type === 'user';
    }
    public function is_admin(){
        return $this->user_type === 'admin';
    }
    public function is_employer(){
        return $this->user_type === 'employer';
    }
    public function is_agent(){
        return $this->user_type === 'agent';
    }

    public function scopeEmployer($query){
        return $query->whereUserType('employer');
    }
    public function scopeAgent($query){
        return $query->whereUserType('agent');
    }
    public function isEmployerFollowed($employer_id = null){
        if ( ! $employer_id || ! Auth::check()){
            return false;
        }

        $user = Auth::user();
        $isFollowed = UserFollowingEmployer::whereUserId($user->id)->whereEmployerId($employer_id)->first();

        if($isFollowed){
            return true;
        }
        return false;
    }

    public function getFollowersAttribute(){
        $followersCount = UserFollowingEmployer::whereEmployerId($this->id)->count();
        if ($followersCount){
            return number_format($followersCount);
        }
        return 0;
    }

    public function getFollowableAttribute(){
        if ( ! Auth::check()){
            return true;
        }

        $user = Auth::user();
        return $this->id !== $user->id;
    }

    public function getLogoUrlAttribute(){
        if ($this->logo){
            return asset('storage/uploads/images/logos/'.$this->logo);
        }
        return asset('assets/images/company.png');
    }

    public function payments(){
        return $this->hasMany(Payment::class);
    }
    public function getPremiumJobsBalanceAttribute($value){
        return $value;
    }

    public function checkJobBalace(){
        $totalPremiumJobsPaid = $this->payments()->success()->sum('premium_job');
        $totalPosted = $this->jobs()->whereIsPremium(1)->count();
        $balance = $totalPremiumJobsPaid - $totalPosted;

        $this->premium_jobs_balance = $balance;
        $this->save();
    }

    public function signed_up_datetime(){
        $created_date_time = $this->created_at->timezone(get_option('default_timezone'))->format(get_option('date_format_custom').' '.get_option('time_format_custom'));
        return $created_date_time;
    }
    public function status_context(){
        $status = $this->active_status;

        $context = '';
        switch ($status){
            case '0':
                $context = 'Pending';
                break;
            case '1':
                $context = 'Active';
                break;
            case '2':
                $context = 'Block';
                break;
        }
        return $context;
    }

}

job/resources/views/admin/add_page.blade.php
@extends('layouts.dashboard')

@section('title_action_btn_gorup')
    <a href="{{route('pages')}}" class="btn btn-primary"><i class="la la-th-list"></i> @lang('app.pages')</a>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="" method="post">
                @csrf

                <div class="form-group {{ $errors->has('title')? 'has-error':'' }}">
                    <div class="col-sm-12">
                        <input type="text" class="form-control {{e_form_invalid_class('title', $errors)}}" id="title" value="{{ old('title') }}" name="title" placeholder="@lang('app.title')">
                        {!! e_form_error('title', $errors) !!}
                    </div>
                </div>


                <div class="form-group {{ $errors->has('post_content')? 'has-error':'' }}">
                    <div class="col-sm-12">
                        <textarea name="post_content" id="post_content" class="form-control {{e_form_invalid_class('post_content', $errors)}}" rows="8">{{ old('post_content') }}</textarea>
                        {!! e_form_error('post_content', $errors) !!}
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-6">
                        <label for="show_in_header_menu" class="checkbox-inline">
                            <input type="checkbox" value="1" id="show_in_header_menu" name="show_in_header_menu">
                            @lang('app.show_in_header_menu')
                        </label>
                    </div>
                    <div class="col-md-6">
                        <label for="show_in_footer_menu" class="checkbox-inline">
                            <input type="checkbox" value="1" id="show_in_footer_menu" name="show_in_footer_menu">
                            @lang('app.show_in_footer_menu')
                        </label>
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-sm-9">
                        <button type="submit" class="btn btn-primary">@lang('app.save_new_page')</button>
                    </div>
                </div>


            </form>



        </div>
    </div>



@endsection


@section('page-js')
    <script src="{{ asset('assets/plugins/ckeditor/ckeditor.js') }}" defer></script>
    <script>
        window.addEventListener('DOMContentLoaded', function() {
            CKEDITOR.replace( 'post_content' );
        });
    </script>
@endsection

job/resources/views/admin/add_post.blade.php
@extends('layouts.dashboard')

@section('title_action_btn_gorup')
    <a href="{{route('posts')}}" class="btn btn-primary"><i class="la la-th-list"></i> @lang('app.posts')</a>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="" method="post" enctype="multipart/form-data">
                @csrf

                <div class="form-group {{ $errors->has('title')? 'has-error':'' }}">
                    <div class="col-sm-12">
                        <input type="text" class="form-control {{e_form_invalid_class('title', $errors)}}" id="title" value="{{ old('title') }}" name="title" placeholder="@lang('app.title')">
                        {!! e_form_error('title', $errors) !!}
                    </div>
                </div>


                <div class="form-group {{ $errors->has('post_content')? 'has-error':'' }}">
                    <div class="col-sm-12">
                        <textarea name="post_content" id="post_content" class="form-control {{e_form_invalid_class('post_content', $errors)}}" rows="8">{{ old('post_content') }}</textarea>
                        {!! e_form_error('post_content', $errors) !!}
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-6">
                        <p>@lang('app.feature_image')</p>
                        <input type="file" name="feature_image">
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-sm-9">
                        <button type="submit" class="btn btn-primary">@lang('app.save_new_page')</button>
                    </div>
                </div>


            </form>



        </div>
    </div>



@endsection


@section('page-js')
    <script src="{{ asset('assets/plugins/ckeditor/ckeditor.js') }}" defer></script>
    <script>
        window.addEventListener('DOMContentLoaded', function() {
            CKEDITOR.replace( 'post_content' );
        });
    </script>
@endsection

job/resources/views/admin/applicants.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="row">
        <div class="col-md-12">

            @if($applications->count())
                <table class="table table-bordered">

                    <tr>
                        <th>@lang('app.name')</th>
                        <th>@lang('app.employer')</th>
                        <th>#</th>
                    </tr>

                    @foreach($applications as $application)
                        <tr>
                            <td>
                                <i class="la la-user"></i> {{$application->name}}
                                <p class="text-muted"><i class="la la-clock-o"></i> {{$application->created_at->format(get_option('date_format'))}} {{$application->created_at->format(get_option('time_format'))}}</p>
                                <p class="text-muted"><i class="la la-envelope-o"></i> {{$application->email}}</p>
                                <p class="text-muted"><i class="la la-phone-square"></i> {{$application->phone_number}}</p>
                                <p class="text-muted"><i class="la la-eye"><a target="_blank" href="{{url('/dashboard/u/cv/view/'.$application->user_id)}}">VIEW CV</a></p>
                            </td>

                            <td>
                                @if( ! empty($application->job->job_title))
                                    <p>
                                        <a href="{{route('job_view', $application->job->job_slug)}}" target="_blank">{{$application->job->job_title}}</a>
                                    </p>
                                @endif

                                @if( ! empty($application->job->employer->company))
                                    <p>{{$application->job->employer->company}}</p>
                                @endif
                            </td>
                            <td>
                                @if( ! $application->is_shortlisted)
                                    <a href="{{route('make_short_list', $application->id)}}" class="btn btn-success"><i class="la la-user-plus"></i> @lang('app.shortlist') </a>
                                @else
                                    <a href="{{route('remove_short_list', $application->id)}}" class="btn btn-success"><i class="la la-user-times"></i> @lang('app.shortlisted') </a>
                                @endif
                            </td>

                        </tr>
                    @endforeach

                </table>


                {!! $applications->links() !!}
            @else
                <div class="row">
                    <div class="col-md-12">
                        <div class="no data-wrap py-5 my-5 text-center">
                            <h1 class="display-1"><i class="la la-frown-o"></i> </h1>
                            <h1>No Data available here</h1>
                        </div>
                    </div>
                </div>
            @endif

        </div>
    </div>



@endsection

job/resources/views/admin/applied_jobs.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="row">
        <div class="col-md-12">

            <table class="table table-bordered">

                <tr>
                    <th>@lang('app.name')</th>
                    <th>@lang('app.employer')</th>
                </tr>

                @foreach($applications as $application)
                    <tr>
                        <td>
                            <i class="la la-user"></i> {{$application->name}}
                            <p class="text-muted"><i class="la la-clock-o"></i> {{$application->created_at->format(get_option('date_format'))}} {{$application->created_at->format(get_option('time_format'))}}</p>
                            <p class="text-muted"><i class="la la-envelope-o"></i> {{$application->email}}</p>
                            <p class="text-muted"><i class="la la-phone-square"></i> {{$application->phone_number}}</p>
                            
                        </td>

                        <td>
                            @if( ! empty($application->job->job_title))
                                <p>
                                    <a href="{{route('job_view', $application->job->job_id)}}" target="_blank">{{$application->job->job_title}}</a>
                                </p>
                            @endif

                            @if( ! empty($application->job->employer->company))
                                <p>{{$application->job->employer->company}}</p>
                            @endif
                        </td>

                    </tr>
                @endforeach

            </table>


            {!! $applications->links() !!}

        </div>
    </div>



@endsection

job/resources/views/admin/categories.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="row">
        <div class="col-md-10">


            <form method="post" action="">
                @csrf

                <div class="form-group row {{ $errors->has('category_name')? 'has-error':'' }}">
                    <label for="category_name" class="col-sm-4 control-label">@lang('app.category_name')</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control {{e_form_invalid_class('category_name', $errors)}}" id="category_name" value="{{ old('category_name') }}" name="category_name" placeholder="@lang('app.category_name')">

                        {!! e_form_error('category_name', $errors) !!}
                    </div>
                </div>


                <div class="form-group row">
                    <div class="col-sm-offset-4 col-sm-8">
                        <button type="submit" class="btn btn-primary">@lang('app.save_new_category')</button>
                    </div>
                </div>

            </form>

        </div>

    </div>


    <div class="row">
        <div class="col-md-12">
            <table class="table table-bordered">
                <tr>
                    <th>@lang('app.category_name')</th>
                    <th>#</th>
                </tr>
                @foreach($categories as $category)
                    <tr>
                        <td>
                            {{ $category->category_name }}
                        </td>
                        <td>
                            <a href="{{ route('edit_categories', $category->id) }}" class="btn btn-info"><i class="la la-pencil"></i> </a>
                            <a href="javascript:;" class="btn btn-danger category_delete" data-id="{{ $category->id }}"><i class="la la-trash"></i> </a>
                        </td>
                    </tr>
                @endforeach
            </table>
        </div>
    </div>



@endsection

job/resources/views/admin/post_edit.blade.php
@extends('layouts.dashboard')

@section('title_action_btn_gorup')
    <a href="{{route('posts')}}" class="btn btn-primary"><i class="la la-th-list"></i> @lang('app.posts')</a>
    <a href="{{route('add_post')}}" class="btn btn-primary"><i class="la la-plus-circle"></i> @lang('app.add_post')</a>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="" method="post" enctype="multipart/form-data">
                @csrf

                <div class="form-group {{ $errors->has('title')? 'has-error':'' }}">
                    <div class="col-sm-12">
                        <input type="text" class="form-control {{e_form_invalid_class('title', $errors)}}" id="title" value="{{$post->title}}" name="title" placeholder="@lang('app.title')">
                        {!! e_form_error('title', $errors) !!}
                    </div>
                </div>

                <div class="form-group {{ $errors->has('post_content')? 'has-error':'' }}">
                    <div class="col-sm-12">
                        <textarea name="post_content" id="post_content" class="form-control {{e_form_invalid_class('post_content', $errors)}}" rows="8">{{$post->post_content}}</textarea>
                        {!! e_form_error('post_content', $errors) !!}
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6">
                        <p>@lang('app.feature_image')</p>
                        @if($post->feature_image_thumb_uri)
                            <div class="post-feature-image-preview-wrap mb-3 mt-3">
                                <img src="{{$post->feature_image_thumb_uri}}" />
                            </div>
                        @endif
                        <input type="file" name="feature_image">
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-9">
                        <button type="submit" class="btn btn-primary">@lang('app.update_page')</button>
                    </div>
                </div>

            </form>



        </div>
    </div>



@endsection


@section('page-js')
    <script src="{{ asset('assets/plugins/ckeditor/ckeditor.js') }}" defer></script>
    <script>
        window.addEventListener('DOMContentLoaded', function() {
            CKEDITOR.replace( 'post_content' );
        });
    </script>
@endsection

job/resources/views/admin/posts.blade.php
@extends('layouts.dashboard')

@section('title_action_btn_gorup')
    <a href="{{route('add_post')}}" class="btn btn-primary"><i class="la la-plus-circle"></i> @lang('app.add_post')</a>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            @if($posts->count())

                <table class="table table-bordered">

                    <tr>
                        <th>@lang('app.title')</th>
                        <th>@lang('app.thumb')</th>
                        <th>#</th>
                    </tr>

                    @foreach($posts as $post)
                        <tr>
                            <td>{{$post->title}}</td>
                            <td width="80">
                                <img src="{{$post->feature_image_thumb_uri}}" class="card-img" />
                            </td>
                            <td>
                                <a href="{{route('post_edit', $post->id)}}" class="btn btn-primary"><i class="la la-pencil-square"></i> @lang('app.edit')</a>
                            </td>
                        </tr>
                    @endforeach

                </table>

                {!! $posts->links() !!}
            @endif

        </div>
    </div>



@endsection

job/resources/views/admin/profile.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="row">
        <div class="col-md-12">

            @if($user->is_employer() || $user->is_agent())
                <div class="profile-company-logo mb-3">
                    <img src="{{$user->logo_url}}" class="img-fluid" style="max-width: 100px;" />
                </div>
            @endif

            <table class="table table-bordered table-striped mb-4">

                <tr>
                    <th>@lang('app.name')</th>
                    <td>{{ $user->name }}</td>
                </tr>

                <tr>
                    <th>@lang('app.email')</th>
                    <td>{{ $user->email }}</td>
                </tr>
                <tr>
                    <th>@lang('app.gender')</th>
                    <td>{{ ucfirst($user->gender) }}</td>
                </tr>
                <tr>
                    <th>@lang('app.phone')</th>
                    <td>{{ $user->phone }}</td>
                </tr>
                <tr>
                    <th>@lang('app.address')</th>
                    <td>{{ $user->address }}</td>
                </tr>
                <tr>
                    <th>@lang('app.country')</th>
                    <td>
                            {{ $user->country_name }}
                    </td>
                </tr>

                <tr>
                    <th>@lang('app.created_at')</th>
                    <td>{{ $user->signed_up_datetime() }}</td>
                </tr>
                <tr>
                    <th>@lang('app.status')</th>
                    <td>{{ $user->status_context() }}</td>
                </tr>
            </table>




            @if($user->is_employer() || $user->is_agent())
                    <h3 class="mb-4">About Company</h3>

                    <table class="table table-bordered table-striped">
                    <tr>
                        <th>@lang('app.state')</th>
                        <td>{{ $user->state_name }}</td>
                    </tr>
                    <tr>
                        <th>@lang('app.city')</th>
                        <td>{{ $user->city }}</td>
                    </tr>

                    <tr>
                        <th>@lang('app.website')</th>
                        <td>{{ $user->website }}</td>
                    </tr>
                    <tr>
                        <th>@lang('app.company')</th>
                        <td>{{ $user->company }}</td>
                    </tr>
                    <tr>
                        <th>@lang('app.company_size')</th>
                        <td>{{company_size($user->company_size)}}</td>
                    </tr>
                    <tr>
                        <th>@lang('app.about_company')</th>
                        <td>{{ $user->about_company }}</td>
                    </tr>
                    <tr>
                        <th>@lang('app.premium_jobs_balance')</th>
                        <td>{{ $user->premium_jobs_balance }}</td>
                    </tr>
                </table>
            @endif


            @if( ! empty($is_user_id_view))
                <a href="{{route('users_edit', $user->id)}}"><i class="la la-pencil-square-o"></i> @lang('app.edit') </a>
            @else
                <a href="{{ route('profile_edit') }}"><i class="la la-pencil-square-o"></i> @lang('app.edit') </a>
            @endif


        </div>
    </div>



@endsection